openapi: 3.0.0
info:
  title: local api
  version: '1.0'
  description: API for the local environment.
servers:
  - url: 'http://localhost:8080'
paths:
  /api/user/signup/:
    post:
      summary: Create a new account
      operationId: post-api-user-create
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  name:
                    type: string
      description: Create a new account with sign up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                password:
                  type: string
                  format: password
                avatarUrl:
                  type: string
                about:
                  type: string
              required:
                - email
                - name
                - password
            examples: {}
    parameters: []
  /api/user/myprofile/:
    get:
      summary: Retrieve login user information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: get-api-user-myprofile
      description: Retrieve login user information
      parameters: []
    parameters: []
  '/api/user/profile/{userId}/':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Retrieve an user detail
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      operationId: get-api-users-userId
      description: ''
    put:
      summary: Update an user detail
      operationId: put-api-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: Own account only
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    patch:
      summary: Partial update an user detail
      operationId: patch-api-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: Own account only
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    delete:
      summary: Delete an user account
      operationId: delete-api-users-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: number
      description: Own account only
  /api/user/approval/:
    get:
      summary: Get friend requests
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FriendRequests'
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-api-user-approval
    post:
      summary: Post a friend request
      operationId: post-api-user-approval
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequests'
  '/api/user/approval/{approvalId}':
    parameters:
      - schema:
          type: string
        name: approvalId
        in: path
        required: true
    put:
      summary: ''
      operationId: put-api-user-approval-approvalId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequests'
    patch:
      summary: ''
      operationId: patch-api-user-approval-approvalId
      responses:
        '200':
          description: OK
  /api/dm/inbox:
    get:
      summary: Get direct messages to myself
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DirectMessages'
      operationId: get-api-dm-inbox
  /api/dm/message/:
    post:
      summary: Post a direct message
      operationId: post-api-dm-message
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectMessages'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DirectMessages'
        description: ''
  /authen/:
    get:
      summary: Token Retrieval endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      operationId: get-authen
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
  /api/posts/:
    get:
      summary: Retrieve a list of posts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
      operationId: get-api-posts
    post:
      summary: ''
      operationId: post-api-posts
      responses:
        '201':
          description: Created
        '':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
  '/api/posts/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: Retrieve a post detail
      tags: []
      responses: {}
      operationId: get-api-posts-postId
    patch:
      summary: ''
      operationId: patch-api-posts-postId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
    delete:
      summary: ''
      operationId: delete-api-posts-postId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  postId:
                    type: integer
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        name:
          type: string
        avatarUrl:
          type: string
        about:
          type: string
    FriendRequests:
      title: FriendRequests
      type: object
      x-examples: {}
      properties:
        askFrom:
          type: integer
        askTo:
          type: integer
        approved:
          type: boolean
          default: 'false'
      required:
        - askFrom
        - askTo
        - approved
    DirectMessages:
      title: DirectMessages
      type: object
      properties:
        sender:
          type: integer
        receiver:
          type: integer
        message:
          type: string
    Post:
      title: Post
      type: object
      properties:
        userId:
          type: integer
        content:
          type: string
      required:
        - userId
        - content
