openapi: 3.0.0
info:
  title: local api
  version: '1.0'
  description: API for the local environment.
servers:
  - url: 'http://localhost:8080'
paths:
  /api/user/create:
    post:
      summary: Create a new account
      operationId: post-api-user-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  email:
                    type: string
                  name:
                    type: string
      description: Create a new account when you sign up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                password:
                  type: string
                  format: password
                avatarUrl:
                  type: string
              required:
                - email
                - name
                - password
            examples: {}
components:
  schemas: {}
